version: '3.1'
services:
  postgres:
    image: postgres:11-alpine
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
    ports:
      - 5432:5432

  redis:
    image: 'redis:latest'
    ports:
      - '6379:6379'
    volumes:
      - './data/redis:/data'
